In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.Series(np.random.randint(1,5),index=[1,2,3,4,5]) #manually creating a series
dt = pd.DataFrame({'number': [1, 2, 3, 4, 5]}, index=[0, 1, 2, 3, 4]) #manually creating a dataframe with index
print(data)
print(dt)

1    4
2    4
3    4
4    4
5    4
dtype: int64
   number
0       1
1       2
2       3
3       4
4       5


In [3]:
#creating a dataframe with random integers
x = pd.DataFrame(np.random.randint(1,5,(3,3)), columns=['a','b','c'],index=(1,2,3))
print(x)
# calculating determinant of the matrix
determinant = np.linalg.det(x.values)
print("Determinant of the matrix is:", determinant)

   a  b  c
1  1  3  1
2  3  2  2
3  2  3  4
Determinant of the matrix is: -17.0


In [4]:
dic = {"mani" : 123, "sai" : 456, "kiran" : 789} #creating a dictionary
df = pd.DataFrame(dic.items(), columns=['Name', 'Number']) #creating a dataframe from dictionary  
print(dic)
print(df)

{'mani': 123, 'sai': 456, 'kiran': 789}
    Name  Number
0   mani     123
1    sai     456
2  kiran     789


In [5]:
d = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]}) #creating a dataframe with two columns
print(d) #printing the dataframe
print(d['a']) # accessing the first column
print(d.iloc[0]) # accessing the first row

   a  b
0  1  4
1  2  5
2  3  6
0    1
1    2
2    3
Name: a, dtype: int64
a    1
b    4
Name: 0, dtype: int64


In [6]:
df1 = pd.Series(['a', 'b', 'c', 'd', 'e'], index=[1, 2, 3, 4, 5]) #creating a series with index
print(df1[1]) #accessing the first element of the series

a


In [7]:
# Creating a manual dataset with some null values
import pandas as pd
manual_data = pd.DataFrame({
    'Name': ['Aarav', 'Ishita', None, 'Rohan', 'Priya'],
    'Age': [25, None, 35, 40, None],
    'Gender': ['M', 'F', 'M', None, 'F']
})
print("Manual Data with Null Values:")
print(manual_data)

# Example of treating null values:
# Filling null values with a default value
manual_data_filled = manual_data.fillna({'Name': 'Unknown', 'Age': manual_data['Age'].mean(), 'Gender': 'Unknown'})
print("\nData after treating null values:")
print(manual_data_filled)

Manual Data with Null Values:
     Name   Age Gender
0   Aarav  25.0      M
1  Ishita   NaN      F
2    None  35.0      M
3   Rohan  40.0   None
4   Priya   NaN      F

Data after treating null values:
      Name        Age   Gender
0    Aarav  25.000000        M
1   Ishita  33.333333        F
2  Unknown  35.000000        M
3    Rohan  40.000000  Unknown
4    Priya  33.333333        F


In [8]:
x = pd.Series([1, 2, 3, 4, 5]) #creating a series with index
y = pd.DataFrame(np.random.randint(1,5,(3,3)), columns=list("abc"),index=(1,2,3)) #creating a dataframe with random integers
print(y)
det = np.linalg.det(y.values) #calculating the determinant of the matrix
det

   a  b  c
1  2  1  1
2  3  4  4
3  3  3  3


2.960594732333755e-16

### Linear Algebra Functions in NumPy
NumPy provides a variety of linear algebra functions to perform operations such as matrix multiplication, determinant calculation, eigenvalues, and more.

In [9]:
import numpy as np

# Example matrix
matrix = np.random.randint(1, 10, (2,2))

# Matrix multiplication
result = np.dot(matrix, matrix)
print("Matrix Multiplication:\n", result)

# Determinant
det = np.linalg.det(matrix)
print("\nDeterminant:", det)

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("\nInverse of the matrix:\n", inverse)

Matrix Multiplication:
 [[43 60]
 [30 43]]

Determinant: 6.999999999999999

Eigenvalues: [9.24264069 0.75735931]
Eigenvectors:
 [[ 0.81649658 -0.81649658]
 [ 0.57735027  0.57735027]]

Inverse of the matrix:
 [[ 0.71428571 -0.85714286]
 [-0.42857143  0.71428571]]


In [10]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randn(5)) #creating a series with random numbers
ser

0    0.496714
1   -0.138264
2    0.647689
3    1.523030
4   -0.234153
dtype: float64

In [11]:
ser.sum()

2.2950148716254297

In [13]:
ser.mean()

0.45900297432508597

In [17]:
x = pd.Series([1, 2, 3, 4, np.nan, None, 0])#creating a series with index
pd.isnull(x)

0    False
1    False
2    False
3    False
4     True
5     True
6    False
dtype: bool

In [ ]:
pd.notnull(x) #opposite of isnull

0     True
1     True
2     True
3     True
4    False
5    False
6     True
dtype: bool

In [ ]:
y = pd.DataFrame({'a': [1, 2, None], 'b': [np.nan, 5, 6]}) #creating a dataframe with two column
y.fillna(0) #filling the null values with 0

Empty DataFrame
Columns: []
Index: [0, 1, 2]