In [18]:
import numpy as np    

In [29]:
np.random.seed(0) # we use seed(0) to make the random numbers reproducible for testing
x = np.random.random(9)
x

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276])

In [ ]:
# max value using numpy
mx = np.max(x)
#same for min value
mn = np.min(x)
# same we use sum for sum of elements
sm = np.sum(x)
print("max value: ", mx)
print("min value: ", mn)
print("sum of elements: ", sm)

max value:  0.9636627605010293
min value:  0.4236547993389047
sum of elements:  5.7742213143196475


In [41]:
#same way we use 2 dimension array
y = np.random.random((3, 3)) 
print("The original array: \n", y)
print("The highest value in each column: ", np.max(y, axis=0))
print("The highest value in each row: ", np.max(y, axis=1))

The original array: 
 [[0.13818295 0.19658236 0.36872517]
 [0.82099323 0.09710128 0.83794491]
 [0.09609841 0.97645947 0.4686512 ]]
The highest value in each column:  [0.82099323 0.97645947 0.83794491]
The highest value in each row:  [0.36872517 0.83794491 0.97645947]
