In [18]:
import numpy as np    

In [29]:
np.random.seed(0) # we use seed(0) to make the random numbers reproducible for testing
x = np.random.random(9)
x

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276])

In [ ]:
# max value using numpy
mx = np.max(x)
#same for min value
mn = np.min(x)
# same we use sum for sum of elements
sm = np.sum(x)
print("max value: ", mx)
print("min value: ", mn)
print("sum of elements: ", sm)

max value:  0.9636627605010293
min value:  0.4236547993389047
sum of elements:  5.7742213143196475


In [41]:
#same way we use 2 dimension array
y = np.random.random((3, 3)) 
print("The original array: \n", y)
print("The highest value in each column: ", np.max(y, axis=0))
print("The highest value in each row: ", np.max(y, axis=1))

The original array: 
 [[0.13818295 0.19658236 0.36872517]
 [0.82099323 0.09710128 0.83794491]
 [0.09609841 0.97645947 0.4686512 ]]
The highest value in each column:  [0.82099323 0.97645947 0.83794491]
The highest value in each row:  [0.36872517 0.83794491 0.97645947]


In [8]:
import numpy as np
data = np.array([1,4])
ones = np.ones(2,dtype= int)
print(data)
print(ones)
print(data + ones)

[1 4]
[1 1]
[2 5]


In [14]:
data.mean()

2.5

In [16]:
df = np.array([1,2,2,3,4,3,5,6,7,0,8,8,10,10])
np.unique(df) # unique values in the array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

## MEAN SQUARE ERROR

In [23]:
p = np.array([1, 2, 3, 4, 5])
a = np.array([1, 2, 3, 4, 6])
predicted = np.reshape(p, (5, 1))
actual = np.reshape(a, (5, 1))
n = len(predicted)
error = (1/n)*np.sum(np.square(predicted - actual))
error

0.2

In [24]:
np.diag([1, 2, 3, 4, 5]) # diagonal matrix with the given values

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])